---
title: "The Black Road RPG v1.39b9 --- Changelog"
author: "Alteisen (Av3n)"
format: html
toc: true
toc-depth: 3
toc-location: left
fontsize: "18px"
page-layout: full
embed-resources: true
css: "TBR.css"
editor: 
  markdown: 
    wrap: 72
---

## General

-   The map now enforces **SD** graphics for all players
-   *Passive abilities* with a cooldown component are updated to display
    the icon's disabled button render while on cooldown. This is because
    there are scenarios where Warcraft 3 does not render the blue
    overlay texture for triggered cooldowns
-   Whenever a sub-goal of the *Lack of Oil* (Aeson) quest is completed:
    The collectable items associated with the sub-goal are now cleaned
    up, rather than at quest completion itself
-   Tweaked the town teleporters' tooltips
-   Teleports from *Alcon*, *Temple of Apollo*, *Phylas*, and *Obelisk
    of Poseidon* now use the same framework as the town teleporters
-   All floating text tag presentations of Essence now use the same
    colour
-   Added the *Statuette of the Tyche* to the *Island of Storms*. You
    can offer the following to the *Statuette* for essence:
    -   *Olympian Gemstone Fragment* for 125 essence
    -   *Two Olympian Gemstone Fragments* for 250 essence
    -   *Three Olympian Gemstone Fragments* for 375 essence
    -   *Gemstone of the Olympians* for 500 essence
-   Acquisition cooldowns for *Titan Fibre* and *Titan Ore*: 30 seconds
    ⇒ 15 seconds
-   Updated the underlying code for the item forging system, that is,
    the metalsmiths. The *only* visible change is that it prints error
    messages in the same style as the regalia forging system's error
    messages
-   Updated the underlying code for the addition and removal of
    triggered abilities for a variety of items. It now explicitly checks
    for the hero typing instead of checking that they are not familiars
    nor banks
-   Updated the buff icons for *Trueshot Aura I* and *Trueshot Aura II*
    (Item Abilities)

## Bug Fixes

-   TBR no longer presents the Warcraft 3 default floating text tag for
    experience gain
-   Misspelling the `-load` chat command no longer loads the previously
    saved hero
-   Updates of the quest multiboard (`-q`) no longer produces
    overlapping rows
-   Health and Mana bonuses for recently implemented items and for
    *Vigorous* (Familiar Skills) now calculates the correct % Health and
    Mana values when applying and removing the bonus(es)

------------------------------------------------------------------------

-   The conversion from a decimal number to an integer number for
    *Transcendence's* (Cleric) number of enhanced auto-attacks outputs a
    rounded integer number <small>(instead of ceiled integer
    number)</small>
-   *Soothing Presence's* (Druid) AoE health and mana % restoration
    works for the full duration
-   *Unbridled Khaos*' (Khaos Champion) bonus auto-attack is typed as
    magical damage <small>(instead of physical damage)</small>

------------------------------------------------------------------------

-   Goldsmith's *Ether Dust* series of consumables now lasts for 10
    minutes as intended
-   *Towering Shield of Athena*, *Unyielding Tower*, *Adamantium Tower*,
    *Adamantium Shield,* and *Shield of Living Bone* auto-attack damage
    block mechanic now works with magical auto-attacks as intended
-   *Atalanta's Hunting Garb*
    -   You can no longer activate the *Swift Return* item ability from
        a familiar's inventory as intended
    -   Grants 40 Agility as intended
-   *Ironwood Regalia XI* grants the intended amount of 1275 Spell Power
-   *Shadow Blade* grants its *Attack Damage +25%* item ability as
    intended
-   Unequipping *Ares' Bloodthirsty Spear* now deactivates the *Eternal
    Hunger* item ability for a wider set of possible scenarios
-   *Mighty Leap* (Midas' Band of Vigor) correctly modifies the users'
    animation speed as intended

------------------------------------------------------------------------

-   *Hyperion* and family's auto-attack pattern of four attacks to the
    closest player hero has been recoded to be more consistently
    enforced. See [Forces of Hell](#forces-of-hell) for an additional
    change to this mechanic
-   *Uranus'* form changes checks if he is alive before completing the
    form change
-   When *Thea* resets, their retaliatory entangling roots mechanic
    consistently works in further attempts
-   When *Rhea* resets, her bonus stats properly set back to 0 points

### Typesetting/Typos

-   *Soul Blade*
-   *Ares' Bloodthristy Spear*
-   *Leather Armor*
-   *Battleforge Regalia VIII* `[8]`
-   *Deathbringer Regalia V* `[5]`
-   *Deathbringer Regalia VI* `[6]`
-   *Battleforge Regalia IX* `[9]`

## Heroes

### Assassin

*Dancing Dagger*

> -   `(NEW)` *Lethal Poison* is now applied to subsequent targets

*Lethal Poison*

> -   Damage type: Physical ⇒ Magical
> -   Agility ratio: 3.0 ⇒ 4.0

*Night Set*

> -   `(REMOVED)` *Lethal Poison* now deals 4.0 / 4.4 / 4.8 / 5.2 / 5.6
>     / 6.0 / 6.4 / 6.8 / 7.2 / 7.6 / 8.0 Agility physical damage over 4
>     seconds
> -   *Dancing Dagger* now applies *Lethal Poison* on each target
> -   `(NEW)` Physical damage dealt by *Assassinate* and *Eviscerate*
>     now ignores half of armor value's damage reduction (if the
>     target's armor is greater than 0)

### Barbarian

### Cleric

### Guardian of Nature

### Khaos Champion

*Khaos Set*

> -   Restore 2.0 Armor Damage Reduction (%) health ⇒ Restore 0.2
>     (Armor + Resist) health

### Magician

### Ranger

### Warlock

<!-- *Ranger* -->

<!-- > *Ironwood Set* -->

<!-- > -->

<!-- > -   `(REMOVED)` Auto-attacks fire 2 (+1 if Agility ≥ 900) more arrows -->

<!-- >     in 0.1s intervals. Each arrow deals the greatest of 0.3 Agility or -->

<!-- >     0.3 Intelligence magical damage to an enemy within a 375 AoE of -->

<!-- >     the target -->

<!-- > -->

<!-- > -   `(NEW)` Gives allies within 450 units 20% bonus damage to their -->

<!-- >     ranged attacks -->

<!-- > -->

<!-- > *Soul-Piercing Shot* -->

<!-- > -->

<!-- > -   `(REMOVED)` Whenever you land a successful auto-attack, you have a -->

<!-- >     15 / 18 / 20 / 21 / 22 / 23 / 24 / 25 % chance to deal an -->

<!-- >     additional 1.75 Agility damage that ignores damage reduction -->

<!-- >     because of armor-type. -->

<!-- > -->

<!-- > -   `(NEW)` Whenever you land your next successful auto-attack: Deal -->

<!-- >     an additional 0.25 Agility + 0.25 Intelligence true damage to the -->

<!-- >     target. -->

<!-- > -->

<!-- > -   `(NEW)` Cooldown: 9 / 8 / 7 / 6 / 5 / 4 / 3 / 2 seconds. -->

<!-- > -->

<!-- > *Strafe* -->

<!-- > -->

<!-- > -   Replaces Prevailing Winds -->

<!-- > -->

<!-- > -   Auto-attacks fire 1 + Agility / 700 bonus arrows at random enemies -->

<!-- >     within 375 AoE of the attacked target. Each bonus arrow deals 0.1 -->

<!-- >     / 0.15 / 0.2 / 0.25 / 0.3 / 0.35 / 0.4 / 0.45 Agility + 0.1 / 0.15 -->

<!-- >     / 0.2 / 0.25 / 0.3 / 0.35 / 0.4 / 0.45 Intelligence physical -->

<!-- >     damage. -->

<!-- *Guardian of Nature* -->

<!-- > *Embolden* -->

<!-- > -->

<!-- > -   Duration: 6.5 seconds ⇒ 15 seconds -->

<!-- > -->

<!-- > -   Cooldown: 15 seconds ⇒ 35 seconds -->

<!-- > -->

<!-- > *Shatter* -->

<!-- > -->

<!-- > -   Replaces *Earth Shock* -->

<!-- > -->

<!-- > -   Mana Cost: 45 / 90 / 135 / 225 / 315 / 450 / 585 / 720 -->

<!-- > -->

<!-- > -   Enemies in a 450 by 200 line are applied Break I for 5 seconds, -->

<!-- >     then are dealt 150 / 250 / 450 / 750 / 1250 / 2000 / 3500 / 6000 + -->

<!-- >     (0.45 / 0.6 / 0.75 / 0.9 / 1.05 / 1.2 / 1.35 / 1.5 STR + 0.15 / -->

<!-- >     0.2 / 0.25 / 0.3 / 0.35 / 0.4 / 0.45 / 0.5 Spell Damage) physical -->

<!-- >     damage. If only a single enemy is struck by Shatter, Break II is -->

<!-- >     applied instead of Break I for 5 seconds. -->

<!-- > -->

<!-- > -   Cooldown: 13 seconds -->

<!-- *Magician* -->

<!-- > -   No longer has jazz (fire) hands -->

<!-- > -->

<!-- > *Freezing Field* -->

<!-- > -->

<!-- > -   `(NOTE)` Freezing Field never dealt reduced damage to subsequent -->

<!-- >     targets -->

<!-- > -->

<!-- > -   Explosions now properly follows a spatially uniform random -->

<!-- >     distribution -->

<!-- > -->

<!-- > -   Updated FX -->

<!-- > -->

<!-- > -   `(NEW)` Now increases Armor and Resist by 1 / 2 / 3 / 4 / 5 / 6 / -->

<!-- >     7 / 8 per 1800 Maximum Health for the duration -->

<!-- > -->

<!-- > -   `(NEW)` Now ensnares targets for 3 seconds the first time they are -->

<!-- >     hit by Freezing Field -->

<!-- > -->

<!-- > -   Mana Cost: 125 / 250 / 400 / 575 / 800 / 1000 / 1000 / 1000 ⇒ 125 -->

<!-- >     / 250 / 400 / 575 / 775 / 1000 / 1250 / 1525 -->

<!-- > -->

<!-- > -   Channel Duration: 4 seconds ⇒ 8 seconds -->

<!-- > -->

<!-- > -   Cooldown: 75 / 70 / 65 / 60 / 55 / 50 / 45 / 45 ⇒ 40 seconds -->

<!-- > -->

<!-- > -   Explosions every 0.05 seconds ⇒ 0.1 seconds -->

<!-- *Barbarian* -->

<!-- > *Mighty Stomp* -->

<!-- > -->

<!-- > -   Cast Point: 0 seconds ⇒ 0.3 seconds -->

<!-- > -->

<!-- > *Rage* -->

<!-- > -->

<!-- > -   `(NEW)` Now on the command card -->

<!-- > -->

<!-- > -   `(REMOVED)` Restore 0.02 \* Level + 0.4 mana when taking a -->

<!-- >     successful auto-attack -->

<!-- > -->

<!-- > -   Base Mana Regen: -0.25 - 4/3 \* 0.01 Level mana per second ⇒ 0 -->

<!-- >     mana per second -->

<!-- > -->

<!-- > -   Whenever you land a successful auto-attack: You restore 0.02 \* -->

<!-- >     Level mana ⇒ 0.03 \* Level mana -->

<!-- > -->

<!-- > *Infuriate* -->

<!-- > -->

<!-- > -   Replaces *Taunt* -->

<!-- > -->

<!-- > -   Mana cost: 0 -->

<!-- > -->

<!-- > -   Taunt all units in a 450 by 200 line for 6 seconds. If at least -->

<!-- >     one unit was taunted, restore 25 mana and an additional 7.5 / 10 / -->

<!-- >     12.5 / 15 / 17.5 / 20 / 22.5 / 25 mana for each unit taunted -->

<!-- > -->

<!-- > -   Cooldown: 17 / 16 / 15 / 14 / 13 / 12 / 11 / 10 seconds -->

<!-- *Cleric* -->

<!-- > *Holy Light* -->

<!-- > -->

<!-- > -   Spell Healing Ratio: 1 ⇒ 0.9 / 0.95 / 1 / 1.05 / 1.1 / 1.15 / 1.2 -->

<!-- >     / 1.25 -->

<!-- > -->

<!-- > -   Cooldown: 4.5 seconds ⇒ 3.5 seconds -->

<!-- > -->

<!-- > *Hallowed Ground* -->

<!-- > -->

<!-- > -   Spell Healing Ratio: 1 ⇒ 1.1 -->

<!-- > -->

<!-- > *Transcendence* -->

<!-- > -->

<!-- > -   Your next Agility / 18 auto-attacks are enhanced ⇒ Your next -->

<!-- >     Agility / 22 auto-attacks are enhanced -->

<!-- > -->

<!-- > -   Heal for 50% total damage inflicted ⇒ Heal for 35% total damage -->

<!-- >     inflicted -->

<!-- *Warlock* -->

<!-- > *Twisted Font* -->

<!-- > -->

<!-- > -   Cooldown: 18.0 / 17.5 / 17.0 / 16.5 / 16.0 / 15.5 / 15.0 / 14.5 -->

<!-- >     seconds ⇒ 32 / 30 / 28 / 26 / 24 / 22 / 20 / 18 seconds -->

<!-- > -->

<!-- > *Shadows Set* -->

<!-- > -->

<!-- > -   Whenever you cast a spell you had 20% chance to increase your -->

<!-- >     Spell Damage by 50% for 20 seconds. ⇒ While Twisted Font is -->

<!-- >     active, your Spell Damage also increases by 50% -->

## Items

::: panel-tabset
## General

-   New items and updated items from **1.39b9** onwrads have the
    following characteristics:
    -   An updated colour coding system for item types
    -   A budget based approach that depends on item level ***and***
        item type for item balancing
    -   Item uniqueness is determined by the item's name
    -   Item restrictions will be written out in full, or use a
        shorthand (e.g. Relics and Olympian Relics)
-   Relics and Olympian Relics now share the same colour code
-   If you target the *Mighty Leap* (Midas' Band of Vigor) and *Blaze o'
    Glory* (Midas' Pendant of Wisdom) abilities on their respective item
    slots, they'll 99% of the time target the user's origin
-   The buff granted by % attack damage bonus item ability found on
    *Blackfire Staff*, *Searing Flame of Prometheus*, *Shadow Blade*,
    and *Blazing Sword of Helios* has been renamed to avoid confusion
    with the buff from the *Command Aura I* / *Command Aura II* item
    abilities
-   A variety of items, primarily consumables and white colour coded
    items, now persist on the map for approximately 10-20 minutes of
    game time before being removed from the map

## Dragonscale

## The Frozen Citadel

## Other

*Gem of Birth*

> -   Icon updated
> -   Model updated

*Gem of Death*

> -   Icon updated
> -   Model updated

*Gem of Life*

> -   Icon updated
> -   Model updated

*Talisman of Addiction*

> -   Strength: 60 ⇒ 30
> -   Agility: 60 ⇒ 30
> -   Intelligence: 60 ⇒ 30

*Warrior's Talisman of Addiction*

> -   Icon updated
> -   Strength: 80 ⇒ 50
> -   Agility: 80 ⇒ 50
> -   `(NO CHANGE)` Intelligence: 2

*Dark Wizard's Dagger*

> -   Level: 85 ⇒ 90
> -   Agility: 50 ⇒ 25
> -   Intelligence: 50 ⇒ 30
> -   Spell Power: 450 ⇒ 0
> -   Item ability codified to *Warmage*
>     -   *Warmage*---Whenever you cast a spell: You restore 50 mana

*Hera's Blessing*

> -   Level: 85 ⇒ 90
> -   Intelligence: 75 ⇒ 0
> -   Spell Power: 500 ⇒ 650
> -   Grants *Brilliance Aura I* instead of "... increases the Mana
>     Regeneration of nearby allies by 10 Mana per second. Warriors will
>     only..."
>     -   *Brilliance Aura I*---Allies within a 450 AoE have their mana
>         regeneration increased by 5 mana per second

*Wizard's Respite*

> -   `(UNCHANGED)` Components: Dark Wizard's Dagger, Hera's Blessing,
>     Gem of the East, Gem of the North, 2 Sea Essence, 2 Heart of Frost
> -   Level: 150 ⇒ 165
> -   Agility: 50 ⇒ 35
> -   Intelligence: 125 ⇒ 75
> -   Spell Power: 950 ⇒ 1100
> -   Mana Regeneration (p/ sec): 0 ⇒ 30
> -   Grants *Warmage* instead of "... Also increases Mana Regeneration
>     by 20 Mana per second, and this effect does not..."
>     -   *Warmage*---Whenever you cast a spell: You restore 50 mana
:::

<!-- -   *Deathchill Blade* -->

<!-- > -   Level: 55 ⇒ 90 -->

<!-- > -->

<!-- > -   Attack Damage: 90 ⇒ 150 -->

<!-- > -->

<!-- > -   Grants Cleave I instead of "\... 35% of your melee base -->

<!-- >     damage\..." -->

<!-- > -->

<!-- > -   Cleave I---Your auto-attacks now deal 0.10 Primary Attribute -->

<!-- >     physical damage in a 200 AoE of the target. Melee only. -->

<!-- -   *Deathchill Greatsword* -->

<!-- > -   Components: Deathchill Blade, Savage War Axe of Hephaestus, -->

<!-- >     Spartan Greatsword, 2 Stone of Heaven, Blood Ruby, 3 Heart of -->

<!-- >     Frost -->

<!-- > -->

<!-- > -   Level: 125 ⇒ 150 -->

<!-- > -->

<!-- > -   Strength: 50 ⇒ 80 -->

<!-- > -->

<!-- > -   Agility: 50 ⇒ 80 -->

<!-- > -->

<!-- > -   Attack Damage: 150 ⇒ 200 -->

<!-- > -->

<!-- > -   Grants Cleave II instead of "\... 35% of your melee base -->

<!-- >     damage\..." -->

<!-- > -->

<!-- > -   Cleave II---Your auto-attacks now deal 0.20 Primary Attribute -->

<!-- >     physical damage in a 200 AoE of the target. Melee only. -->

<!-- -   *Sword of the Olympians* -->

<!-- > Attack Damage: 100 ⇒ 150 -->

<!-- -   The *Talisman* and *Dragonscale* line of items now only follows the -->

<!--     item name uniqueness rule for item restrictions -->

<!-- -   *Midnight Cloak* -->

<!-- > -   Previously Orb of Chill Midnight -->

<!-- > -->

<!-- > -   Level: 55 ⇒ 90 -->

<!-- > -->

<!-- > -   Strength: 10 ⇒ 0 -->

<!-- > -->

<!-- > -   Agility: 10 ⇒ 0 -->

<!-- > -->

<!-- > -   Intelligence: 10 ⇒ 20 -->

<!-- > -->

<!-- > -   Health Regeneration: 30 ⇒ 0 per second -->

<!-- > -->

<!-- > -   Mana: 0 ⇒ 200 -->

<!-- > -->

<!-- > -   Armor: 0 ⇒ 20 -->

<!-- > -->

<!-- > -   Grants Mana Shield instead of Mana Regeneration IX -->

<!-- > -->

<!-- > -   Mana Shield---Activate to convert 20% of your current mana into a -->

<!-- >     post-mitigation damage shield for 5 seconds. Cooldown: 60 seconds. -->

<!-- -   *Amphirite's Cloak* -->

<!-- > -   Components: Midnight Cloak, Circlet of the Mother Goddess, 2 Stone -->

<!-- >     of Heaven, 2 Heart of Frost, 2 Sea Essence -->

<!-- > -->

<!-- > -   Level: 150 -->

<!-- > -->

<!-- > -   Intelligence: 40 -->

<!-- > -->

<!-- > -   Mana: 2000 -->

<!-- > -->

<!-- > -   Mana Regeneration: 20 mana per second -->

<!-- > -->

<!-- > -   Armor: 50 -->

<!-- > -->

<!-- > -   Mana Shield---Activate to convert 20% of your current mana into a -->

<!-- >     post-mitigation damage shield for 5 seconds. Cooldown: 60 seconds. -->

<!-- -   *Sword of the Olympians* -->

<!-- > -   Attack Damage: 100 ⇒ 125 -->

<!-- > -->

<!-- > -   Attack Speed: 150% ⇒ 125% -->

<!-- -   *Chillstone Ring* -->

<!-- > -   Level: 55 ⇒ 90 -->

<!-- > -->

<!-- > -   Strength: 15 ⇒ 20 -->

<!-- > -->

<!-- > -   Agility: 15 ⇒ 20 -->

<!-- > -->

<!-- > -   Intelligence: 15 ⇒ 20 -->

<!-- > -->

<!-- > -   Health: 500 ⇒ 0 -->

<!-- > -->

<!-- > -   Spell Power: 300 ⇒ 350 -->

<!-- -   *Scepter of the Ice Queen* -->

<!-- > -   Level: 55 ⇒ 90 -->

<!-- > -->

<!-- > -   Intelligence: 0 ⇒ 50 -->

<!-- > -->

<!-- > -   Attack Damage: 25 ⇒ 0 -->

<!-- > -->

<!-- > -   Attack Speed: 25 ⇒ 0 -->

<!-- > -->

<!-- > -   Spell Healing: 600 ⇒ 700 -->

<!-- -   *Aegis of the Frozen Citadel* -->

<!-- > -   Previously Ring of the Frozen Citadel -->

<!-- > -->

<!-- > -   Components: Ring of the Frozen Citadel, Iron Will of Hephaestus, 2 -->

<!-- >     Stone of Heaven, 2 Heart of Frost, 2 Sea Essence -->

<!-- > -->

<!-- > -   Level 105 ⇒ 150 -->

<!-- > -->

<!-- > -   Strength: 25 ⇒ 0 -->

<!-- > -->

<!-- > -   Agility: 25 ⇒ 0 -->

<!-- > -->

<!-- > -   Intelligence: 25 ⇒ 0 -->

<!-- > -->

<!-- > -   Health 0 ⇒ 3000 -->

<!-- > -->

<!-- > -   Health Regeneration (p/ sec): 30 ⇒ 0 -->

<!-- > -->

<!-- > -   Armor: 40 ⇒ 60 -->

<!-- > -->

<!-- > -   Resist: 0 ⇒ 60 -->

<!-- > -->

<!-- > -   Spell Power: 300 ⇒ 0 -->

<!-- > -->

<!-- > -   No longer grants Mana Regeneration VIII -->

<!-- > -->

<!-- > -   Grants Frigid Aura II instead of "In addition, any enemy that -->

<!-- >     strikes you\..." -->

<!-- > -->

<!-- > -   Frigid Aura II---Enemies within a 450 AoE have their attack speed -->

<!-- >     reduced by 15% and movement speed reduced by 30% -->

<!-- > -->

<!-- > -   No longer class restricted -->

<!-- -   *White Dragonscale Ring of Serious Addiction* -->

<!-- > -   Craft at: Locris -->

<!-- > -->

<!-- > -   Components: White Dragonscale Ring of Addiction; Frozen Ring of -->

<!-- >     the Ice Queen; Gem of the North; Stone of Heaven -->

<!-- > -->

<!-- > -   Level: 180 -->

<!-- > -->

<!-- > -   Strength: 70 -->

<!-- > -->

<!-- > -   Agility: 70 -->

<!-- > -->

<!-- > -   Intelligence: 50 -->

<!-- > -->

<!-- > -   Resist: 80 -->

<!-- > -->

<!-- > -   Grants Frigid Aura I -->

<!-- > -->

<!-- > -   Frigid Aura I---Enemies within a 450 AoE have their attack speed -->

<!-- >     reduced by 7.5% and movement speed reduced by 15% -->

<!-- -   *Chillstone Ring of Midnight* -->

<!-- > -   Components: Chillstone Ring, Robes of Delphi, 2 Stone of Heaven, 2 -->

<!-- >     Heart of Frost, 2 Sea Essence -->

<!-- > -->

<!-- > -   Level: 135 -->

<!-- > -->

<!-- > -   Strength: 45 -->

<!-- > -->

<!-- > -   Agility: 45 -->

<!-- > -->

<!-- > -   Intelligence: 45 -->

<!-- > -->

<!-- > -   Spell Power: 1200 -->

<!-- -   *Scepter of the Chosen Ones* -->

<!-- > -   Components: Scepter of the Ice Queen, Hera's Blessing, Priam's -->

<!-- >     Scepter, 2 Stone of Heaven, Blood Ruby, 3 Heart of Frost -->

<!-- > -->

<!-- > -   Level: 120 ⇒ 150 -->

<!-- > -->

<!-- > -   Intelligence: 80 -->

<!-- > -->

<!-- > -   `(NO CHANGE)` Attack Damage: 40 -->

<!-- > -->

<!-- > -   `(NO CHANGE)` Attack Speed: 40% -->

<!-- > -->

<!-- > -   Spell Damage: 800 ⇒ 700 -->

<!-- > -->

<!-- > -   Spell Healing: 800 ⇒ 1400 -->

<!-- > -->

<!-- > -   `(NEW)` Brilliance Aura II---Allies within a 450 AoE have their -->

<!-- >     mana regeneration increased by 15 mana per second. -->

<!-- -   *Green Dragonscale* -->

<!-- > -   Previously Green Dragonscale Ring -->

<!-- > -->

<!-- > -   Level: 55 ⇒ 120 -->

<!-- > -->

<!-- > -   Strength: 25 ⇒ 20 -->

<!-- > -->

<!-- > -   Agility: 40 ⇒ 0 -->

<!-- > -->

<!-- > -   Intelligence: 10 ⇒ 65 -->

<!-- > -->

<!-- > -   Resist: 35 ⇒ 20 -->

<!-- -   *White Dragonscale* -->

<!-- > -   Previously White Dragonscale Ring -->

<!-- > -->

<!-- > -   Level: 55 ⇒ 120 -->

<!-- > -->

<!-- > -   Strength: 25 ⇒ 40 -->

<!-- > -->

<!-- > -   Agility: 0 ⇒ 40 -->

<!-- > -->

<!-- > -   Intelligence: 50 ⇒ 20 -->

<!-- > -->

<!-- > -   Resist: 35 ⇒ 20 -->

<!-- -   *Red Dragonscale Ring of Addiction* -->

<!-- > -   Level: 115 ⇒ 135 -->

<!-- > -->

<!-- > -   Components: Red Dragonscale; Warrior's Talisman of Addiction; -->

<!-- >     Burning Heart of Ladon; Blood Ruby; Sea Essence; Sea Essence -->

<!-- > -->

<!-- > -   Strength: 130 ⇒ 100 -->

<!-- > -->

<!-- > -   Agility: 105 ⇒ 100 -->

<!-- > -->

<!-- > -   Intelligence: 3 ⇒ 4 -->

<!-- > -->

<!-- > -   Resist: 50 ⇒ 45 -->

<!-- -   *Green Dragonscale Ring of Addiction* -->

<!-- > -   Level: 115 ⇒ 135 -->

<!-- > -->

<!-- > -   Components: Green Dragonscale; Talisman of Addiction; Burning -->

<!-- >     Heart of Ladon; Blood Ruby; Sea Essence; Sea Essence -->

<!-- > -->

<!-- > -   Strength: 85 ⇒ 50 -->

<!-- > -->

<!-- > -   Agility: 100 ⇒ 30 -->

<!-- > -->

<!-- > -   Intelligence: 70 ⇒ 95 -->

<!-- > -->

<!-- > -   Resist: 50 ⇒ 45 -->

<!-- -   *White Dragonscale Ring of Addiction* -->

<!-- > -   Level: 115 ⇒ 135 -->

<!-- > -->

<!-- > -   Components: White Dragonscale; Talisman of Addiction; Burning -->

<!-- >     Heart of Ladon; Blood Ruby; Sea - Essence; Sea Essence -->

<!-- > -->

<!-- > -   Strength: 85 ⇒ 70 -->

<!-- > -->

<!-- > -   Agiltiy: 60 ⇒ 70 -->

<!-- > -->

<!-- > -   Intelligence: 110 ⇒ 50 -->

<!-- > -->

<!-- > -   Resist: 50 ⇒ 45 -->

<!-- -   *Red Dragonscale Ring of Serious Addiction* -->

<!-- > -   Previously Warrior's Talisman of Serious Addiction -->

<!-- > -->

<!-- > -   Craft at: Athens ⇒ Locris -->

<!-- > -->

<!-- > -   Cost: 10000 / 20000 ⇒ 0 / 0 -->

<!-- > -->

<!-- > -   Components: Red Dragonscale Ring of Addiction; Deathchill Blade; -->

<!-- >     Gem of the South; Stone of Heaven -->

<!-- > -->

<!-- > -   Level: 200 ⇒ 180 -->

<!-- > -->

<!-- > -   Strength: 160 ⇒ 100 -->

<!-- > -->

<!-- > -   Agility: 160 ⇒ 100 -->

<!-- > -->

<!-- > -   Attack Damage: 0 ⇒ 75 -->

<!-- > -->

<!-- > -   `(UNCHANGED)` Intelligence: 4 -->

<!-- > -->

<!-- > -   Resist: 65 ⇒ 60 -->

<!-- > -->

<!-- > -   Grants Cleave I instead of "\... 35% of your melee base -->

<!-- >     damage\..." -->

<!-- > -->

<!-- > -   Cleave I---Your auto-attacks now deal 0.10 Primary Attribute -->

<!-- >     physical damage in a 150 AoE of the target. Melee only -->

<!-- -   *Green Dragonscale Ring of Serious Addiction* -->

<!-- > -   Previously Talisman of Serious Addiction -->

<!-- > -->

<!-- > -   Craft at: Athens ⇒ Locris -->

<!-- > -->

<!-- > -   Cost: 10000 / 20000 ⇒ 0 / 0 -->

<!-- > -->

<!-- > -   Level: 200 ⇒ 180 -->

<!-- > -->

<!-- > -   Components: Green Dragonscale Ring of Addiction; Chillstone Ring; -->

<!-- >     Gem of the East; Stone of Heaven -->

<!-- > -->

<!-- > -   Strength: 120 ⇒ 60 -->

<!-- > -->

<!-- > -   Agility: 120 ⇒ 30 -->

<!-- > -->

<!-- > -   Intelligence: 120 ⇒ 95 -->

<!-- > -->

<!-- > -   Resist: 65 ⇒ 60 -->

<!-- > -->

<!-- > -   Spell Power: 500 ⇒ 700 -->

## Forces of Hell {#forces-of-hell}

-   Added a leash check for rewarding Essence from the *Hallowed One*
    and *Manslayer & Lightbane* fights
-   *Hyperion* and family's auto-attack pattern of four attacks now
    checks for player heroes ***and*** units
-   If at least one *Minotaur Stronghold* was kept alive upon
    *Hyperion's* defeat: Each participant receives 2 additional stat
    points for each *Minotaur Stronghold* that was kept alive
-   In light of the stat block adjustments in **v1.39b8**, the 3000
    crafting materials previously granted by defeating *Hades* has been
    redistributed as follows:
    -   *Rhea*: 250 crafting materials
    -   *Oceanus*: 500 crafting materials
    -   *Gaea*: 750 crafting materials
    -   *Hades*: 1500 crafting materials
